#!/usr/bin/env ruby

require "bundler/setup"
require "thor"
require "configruous"

class CLI < Thor
  class_option :'dry-run', type: :boolean, desc: "Don't actually make changes", default: true

  desc "version", "Get the current Version of Configruous"
  def version
    puts Configruous::VERSION
  end

  desc "restore ENVIRONMENT FILENAME", "Restore a configuration file from SSM"
  def restore(environment, filename)
    if Pathname.new(filename).exist?
      puts '** This is a dry run **' if options[:'dry-run']
      puts '** Rerun with --no-dry-run to commit changes **' if options[:'dry-run']
      Configruous::FileFactory.load(filename, environment: environment).diff_print_restore
    end
    Configruous::RestoreFileFromSSM.new(environment, filename).save! unless options[:'dry-run']
  end

  desc "upload ENVIRONMENT FILENAME", "Store Configuration in SSM"
  def upload(environment, filename)
    file_obj = Configruous::FileFactory.load(filename, environment: environment)
    puts '** This is a dry run **' if options[:'dry-run']
    puts '** Rerun with --no-dry-run to commit changes **' if options[:'dry-run']
    file_obj.diff_print
    file_obj.store! unless options[:'dry-run']
  end

end

CLI.start(ARGV)
