#!/usr/bin/env ruby

require "bundler/setup"
require "hanami/cli"
require "configruous"

module Configruous
  module CLI
    module Commands
      extend Hanami::CLI::Registry

      class Version < Hanami::CLI::Command
        desc "Print Version"
        def call(*)
          puts Configruous::VERSION
        end
      end

      class RestoreFile < Hanami::CLI::Command
        desc "Restore a configuration file from SSM"
        argument :filename, required: true, desc: "Filename to restore"
        argument :environment, required: true, desc: "Environment to restore to"
        def call(environment:, filename:)
          Configruous::RestoreFileFromSSM.new(environment, filename).save!
        end
      end

      class UploadFile < Hanami::CLI::Command
        desc "Store Configuration in SSM"
        argument :filename, required: true, desc: "Filename to restore"
        argument :environment, required: true, desc: "Environment to store to"
        def call(environment:, filename:)
          file_obj = Configruous::FileFactory.load(filename, environment: environment)
          file_obj.diff_print
          file_obj.store!
        end
      end

      register "version", Version, aliases: ["v", "-v", "--version"]
      register "restore", RestoreFile
      register "upload", UploadFile
    end
  end
end

Hanami::CLI.new(Configruous::CLI::Commands).call
